// Mocks generated by Mockito 5.4.6 from annotations
// in intera_edu/test/notifiers/feed_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:intera_edu/domain/entities/post.dart' as _i4;
import 'package:intera_edu/domain/repositories/feed_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePaginatedResult_0<T> extends _i1.SmartFake
    implements _i2.PaginatedResult<T> {
  _FakePaginatedResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FeedRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedRepository extends _i1.Mock implements _i2.FeedRepository {
  MockFeedRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.PaginatedResult<_i4.Post>> getFeed({
    required String? scope,
    String? cursor,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFeed, [], {
              #scope: scope,
              #cursor: cursor,
              #limit: limit,
            }),
            returnValue: _i3.Future<_i2.PaginatedResult<_i4.Post>>.value(
              _FakePaginatedResult_0<_i4.Post>(
                this,
                Invocation.method(#getFeed, [], {
                  #scope: scope,
                  #cursor: cursor,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.PaginatedResult<_i4.Post>>);

  @override
  _i3.Future<String> createPost({
    required String? content,
    String? scope = 'global',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #content: content,
              #scope: scope,
            }),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#createPost, [], {
                  #content: content,
                  #scope: scope,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> deletePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [postId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addReaction(String? postId, String? reactionType) =>
      (super.noSuchMethod(
            Invocation.method(#addReaction, [postId, reactionType]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeReaction(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#removeReaction, [postId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.PaginatedResult<_i4.Comment>> getComments(
    String? postId, {
    String? cursor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getComments, [postId], {#cursor: cursor}),
            returnValue: _i3.Future<_i2.PaginatedResult<_i4.Comment>>.value(
              _FakePaginatedResult_0<_i4.Comment>(
                this,
                Invocation.method(#getComments, [postId], {#cursor: cursor}),
              ),
            ),
          )
          as _i3.Future<_i2.PaginatedResult<_i4.Comment>>);

  @override
  _i3.Future<void> addComment(
    String? postId,
    String? content, {
    String? parentCommentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addComment,
              [postId, content],
              {#parentCommentId: parentCommentId},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
